POST http://localhost:3001/signup
Content-Type: application/json

{
    "username": "Gokul",
    "email": "gokulpr47@gmail.com",
    "password": "23416823"
}

###

POST http://localhost:3001/signin
Content-Type: application/json

{
    "email": "gokulpr47@gmail.com",
    "password": "23416823"
}